language: node_js
node_js:
  - "node"
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script:
- npm run testncov
after_success:
- cat ./node_modules/lcov.info | ./node_modules/coveralls/bin/coveralls.js
